PALABRA_RESERVADA      programa                 linea=1    columna=1
IDENTIFICADOR          monitoreo_clima          linea=1    columna=10
PUNTO_Y_COMA           ;                        linea=1    columna=25
TIPO                   entero                   linea=2    columna=1
IDENTIFICADOR          distancia                linea=2    columna=8
PUNTO_Y_COMA           ;                        linea=2    columna=17
TIPO                   decimal                  linea=3    columna=1
IDENTIFICADOR          viento                   linea=3    columna=9
PUNTO_Y_COMA           ;                        linea=3    columna=15
TIPO                   cadena                   linea=4    columna=1
IDENTIFICADOR          zona                     linea=4    columna=8
PUNTO_Y_COMA           ;                        linea=4    columna=12
TIPO                   booleano                 linea=5    columna=1
IDENTIFICADOR          alerta_activa            linea=5    columna=10
PUNTO_Y_COMA           ;                        linea=5    columna=23
IDENTIFICADOR          distancia                linea=6    columna=1
OPERADOR_ASIGNACION    =                        linea=6    columna=11
NUMERO_ENTERO          120                      linea=6    columna=13
PUNTO_Y_COMA           ;                        linea=6    columna=16
IDENTIFICADOR          viento                   linea=7    columna=1
OPERADOR_ASIGNACION    =                        linea=7    columna=8
NUMERO_DECIMAL         85.5                     linea=7    columna=10
PUNTO_Y_COMA           ;                        linea=7    columna=14
IDENTIFICADOR          zona                     linea=8    columna=1
OPERADOR_ASIGNACION    =                        linea=8    columna=6
CADENA_LITERAL         NORTE                    linea=8    columna=8
PUNTO_Y_COMA           ;                        linea=8    columna=15
IDENTIFICADOR          alerta_activa            linea=9    columna=1
OPERADOR_ASIGNACION    =                        linea=9    columna=15
BOOLEANO_LITERAL       verdadero                linea=9    columna=17
PUNTO_Y_COMA           ;                        linea=9    columna=26
PALABRA_RESERVADA      si                       linea=10   columna=1
IDENTIFICADOR          viento                   linea=10   columna=4
OPERADOR_RELACIONAL    >                        linea=10   columna=11
NUMERO_ENTERO          70                       linea=10   columna=13
PALABRA_RESERVADA      entonces                 linea=10   columna=16
PALABRA_RESERVADA      alerta                   linea=11   columna=1
PARENTESIS_IZQUIERDO   (                        linea=11   columna=7
CADENA_LITERAL         Tormenta detectada en    linea=11   columna=8
OPERADOR_ARITMETICO    +                        linea=11   columna=33
IDENTIFICADOR          zona                     linea=11   columna=35
PARENTESIS_DERECHO     )                        linea=11   columna=39
PUNTO_Y_COMA           ;                        linea=11   columna=40
PALABRA_RESERVADA      fin                      linea=12   columna=1
PALABRA_RESERVADA      mientras                 linea=13   columna=1
IDENTIFICADOR          distancia                linea=13   columna=10
OPERADOR_RELACIONAL    >                        linea=13   columna=20
NUMERO_ENTERO          0                        linea=13   columna=22
PALABRA_RESERVADA      hacer                    linea=13   columna=24
IDENTIFICADOR          distancia                linea=14   columna=1
OPERADOR_ASIGNACION    =                        linea=14   columna=11
IDENTIFICADOR          distancia                linea=14   columna=13
OPERADOR_ARITMETICO    -                        linea=14   columna=23
NUMERO_ENTERO          30                       linea=14   columna=25
PUNTO_Y_COMA           ;                        linea=14   columna=27
PALABRA_RESERVADA      fin                      linea=15   columna=1
PALABRA_RESERVADA      reporte                  linea=16   columna=1
PARENTESIS_IZQUIERDO   (                        linea=16   columna=8
CADENA_LITERAL         Proceso finalizado       linea=16   columna=9
PARENTESIS_DERECHO     )                        linea=16   columna=29
PUNTO_Y_COMA           ;                        linea=16   columna=30
FIN_DE_ARCHIVO         EOF                      linea=16   columna=31
