PROGRAMA           'programa'               line=1    column=1
IDENTIFIER         'radar'                  line=1    column=10
SEMICOLON          ';'                      line=1    column=15
ENTERO             'entero'                 line=3    column=1
IDENTIFIER         'contador'               line=3    column=8
ASSIGN             '='                      line=3    column=17
INTEGER            '10'                     line=3    column=19
SEMICOLON          ';'                      line=3    column=21
DECIMAL            'decimal'                line=4    column=1
IDENTIFIER         'promedio'               line=4    column=9
ASSIGN             '='                      line=4    column=18
DECIMAL_LITERAL    '42.75'                  line=4    column=20
SEMICOLON          ';'                      line=4    column=25
CADENA             'cadena'                 line=5    column=1
IDENTIFIER         'mensaje'                line=5    column=8
ASSIGN             '='                      line=5    column=16
STRING             'Radar listo'            line=5    column=18
SEMICOLON          ';'                      line=5    column=31
BOOLEANO           'booleano'               line=6    column=1
IDENTIFIER         'activo'                 line=6    column=10
ASSIGN             '='                      line=6    column=17
VERDADERO          'verdadero'              line=6    column=19
SEMICOLON          ';'                      line=6    column=28
SI                 'si'                     line=12   column=1
LEFT_PAREN         '('                      line=12   column=4
IDENTIFIER         'contador'               line=12   column=5
GREATER_EQUAL      '>='                     line=12   column=14
INTEGER            '10'                     line=12   column=17
RIGHT_PAREN        ')'                      line=12   column=19
ENTONCES           'entonces'               line=12   column=21
ALERTA             'alerta'                 line=13   column=5
SEMICOLON          ';'                      line=13   column=11
FIN                'fin'                    line=14   column=1
MIENTRAS           'mientras'               line=16   column=1
LEFT_PAREN         '('                      line=16   column=10
IDENTIFIER         'contador'               line=16   column=11
NOT_EQUAL          '!='                     line=16   column=20
INTEGER            '0'                      line=16   column=23
RIGHT_PAREN        ')'                      line=16   column=24
HACER              'hacer'                  line=16   column=26
IDENTIFIER         'contador'               line=17   column=5
ASSIGN             '='                      line=17   column=14
IDENTIFIER         'contador'               line=17   column=16
MINUS              '-'                      line=17   column=25
INTEGER            '1'                      line=17   column=27
SEMICOLON          ';'                      line=17   column=28
REPORTE            'reporte'                line=18   column=5
SEMICOLON          ';'                      line=18   column=12
FIN                'fin'                    line=19   column=1
EOF                ''                       line=20   column=1
