PROGRAMA           'programa'               line=1    column=1
IDENTIFIER         'radar'                  line=1    column=10
SEMICOLON          ';'                      line=1    column=15
ENTERO             'entero'                 line=3    column=1
IDENTIFIER         'contador'               line=3    column=8
ASSIGN             '='                      line=3    column=17
INTEGER            '10'                     line=3    column=19
SEMICOLON          ';'                      line=3    column=21
CADENA             'cadena'                 line=4    column=1
IDENTIFIER         'titulo'                 line=4    column=8
ASSIGN             '='                      line=4    column=15
STRING             'Radar'                  line=4    column=17
SEMICOLON          ';'                      line=4    column=24
ENTERO             'entero'                 line=5    column=1
IDENTIFIER         'contador'               line=5    column=8
ASSIGN             '='                      line=5    column=17
INTEGER            '20'                     line=5    column=19
SEMICOLON          ';'                      line=5    column=21
DECIMAL            'decimal'                line=6    column=1
IDENTIFIER         'promedio'               line=6    column=9
ASSIGN             '='                      line=6    column=18
IDENTIFIER         'titulo'                 line=6    column=20
SEMICOLON          ';'                      line=6    column=26
SI                 'si'                     line=8    column=1
LEFT_PAREN         '('                      line=8    column=4
IDENTIFIER         'contador'               line=8    column=5
PLUS               '+'                      line=8    column=14
INTEGER            '1'                      line=8    column=16
RIGHT_PAREN        ')'                      line=8    column=17
ENTONCES           'entonces'               line=8    column=19
ALERTA             'alerta'                 line=9    column=5
LEFT_PAREN         '('                      line=9    column=11
IDENTIFIER         'contador'               line=9    column=12
RIGHT_PAREN        ')'                      line=9    column=20
SEMICOLON          ';'                      line=9    column=21
FIN                'fin'                    line=10   column=1
EOF                ''                       line=11   column=1
