PROGRAMA           'programa'               line=1    column=1
IDENTIFIER         'radar'                  line=1    column=10
SEMICOLON          ';'                      line=1    column=15
ENTERO             'entero'                 line=3    column=1
IDENTIFIER         'contador'               line=3    column=8
ASSIGN             '='                      line=3    column=17
INTEGER            '10'                     line=3    column=19
SI                 'si'                     line=5    column=1
LEFT_PAREN         '('                      line=5    column=4
IDENTIFIER         'contador'               line=5    column=5
GREATER_EQUAL      '>='                     line=5    column=14
INTEGER            '10'                     line=5    column=17
RIGHT_PAREN        ')'                      line=5    column=19
ENTONCES           'entonces'               line=5    column=21
ALERTA             'alerta'                 line=6    column=5
LEFT_PAREN         '('                      line=6    column=11
STRING             'ok'                     line=6    column=12
RIGHT_PAREN        ')'                      line=6    column=16
SEMICOLON          ';'                      line=6    column=17
FIN                'fin'                    line=7    column=1
EOF                ''                       line=8    column=1
